---
title: "PCA analysis"
author:
- name: Xiaotao Shen (https://www.shenxt.info/)
date: "Created on 2021-12-04 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{pca_analysis}
  %\VignettePackage{massqc}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```

# **Data preparation**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
library(massdataset)
library(demodata)
library(tidyverse)
library(massstat)
data("liver_aging_pos", package = "demodata")
liver_aging_pos
```

# **PCA analysis**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}

liver_aging_pos %>%
  run_pca(frame = TRUE)

liver_aging_pos %>%
  scale() %>% 
  run_pca(color_by = "group",
          loadings = TRUE) +
  ggsci::scale_fill_lancet() +
  ggsci::scale_color_lancet() 

liver_aging_pos %>%
  activate_mass_dataset(what = "sample_info") %>% 
  dplyr::filter(class == "Subject") %>% 
  scale %>%
  run_pca(color_by = "group", frame = TRUE) +
  ggsci::scale_fill_lancet() +
  ggsci::scale_color_lancet() +
  ggrepel::geom_text_repel(aes(label = sample_id))
```


